<?php
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_user-fields',
		'title' => 'User Fields',
		'fields' => array (
			array (
				'key' => 'field_57defc3a86004',
				'label' => 'Certified',
				'name' => 'certified',
				'type' => 'checkbox',
				'choices' => array (
					50 => '50 Percent',
					100 => '100 Percent',
					'seal' => 'Hawaii Seal',
				),
				'default_value' => '',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_57cdfbeef278a',
				'label' => 'Type Of Business',
				'name' => 'type_of_business',
				'type' => 'checkbox',
				'choices' => array (
					'grower' => 'grower',
					'distributor' => 'distributor',
					'wholesaler' => 'wholesaler',
					'processor' => 'processor',
					'manufacturer' => 'manufacturer',
					'retailer' => 'retailer',
				),
				'default_value' => '',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_57defc0d86003',
				'label' => 'Help',
				'name' => '',
				'type' => 'message',
				'message' => 'Help us setup your Made in Hawaii producer profile',
			),
			array (
				'key' => 'field_57c670d559d68',
				'label' => 'Address',
				'name' => 'address',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57c670dc59d69',
				'label' => 'City',
				'name' => 'city',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57c670e259d6a',
				'label' => 'State',
				'name' => 'state',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57c670e859d6b',
				'label' => 'Zip',
				'name' => 'zip',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57c670ee59d6c',
				'label' => 'Island',
				'name' => 'island',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57c670f559d6d',
				'label' => 'Primary Phone Number',
				'name' => 'phone1',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57c670fd59d6e',
				'label' => 'Secondary Phone Number',
				'name' => 'phone2',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			// array (
			// 	'key' => 'field_57c6710359d6f',
			// 	'label' => 'Fax_Pre',
			// 	'name' => 'fax_pre',
			// 	'type' => 'text',
			// 	'default_value' => '',
			// 	'placeholder' => '',
			// 	'prepend' => '',
			// 	'append' => '',
			// 	'formatting' => 'html',
			// 	'maxlength' => '',
			// ),
			// array (
			// 	'key' => 'field_57c6710b59d70',
			// 	'label' => 'Fax',
			// 	'name' => 'fax',
			// 	'type' => 'text',
			// 	'default_value' => '',
			// 	'placeholder' => '',
			// 	'prepend' => '',
			// 	'append' => '',
			// 	'formatting' => 'html',
			// 	'maxlength' => '',
			// ),
			array (
				'key' => 'field_57c6711159d71',
				'label' => 'Website',
				'name' => 'website',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57c6711c59d72',
				'label' => 'Email',
				'name' => 'email',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57c6712959d74',
				'label' => 'Country',
				'name' => 'country',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57c6712e59d75',
				'label' => 'Established Year',
				'name' => 'established_year',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_57cdfc28f278b',
				'label' => 'Services',
				'name' => 'services',
				'type' => 'checkbox',
				'choices' => array (
					'mailorder' => 'Mail Order',
					'delivery' => 'Delivery',
					'packing' => 'Packing',
					'growing' => 'Growing',
					'labeling' => 'Labeling',
					'bulk' => 'Bulk',
					'retail' => 'Retail',
				),
				'default_value' => '',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_57cdfc59f278c',
				'label' => 'Market',
				'name' => 'market',
				'type' => 'checkbox',
				'choices' => array (
					'hawaii' => 'Hawaii',
					'guam' => 'Guam',
					'china' => 'China',
					'australia' => 'Australia',
					'usmain' => 'United States',
					'japan' => 'Japan',
					'hongkong' => 'Hong Kong',
					'europe' => 'Europe',
					'canada' => 'Canada',
					'korea' => 'Korea',
					'seasia' => 'South East Asia',
				),
				'default_value' => '',
				'layout' => 'horizontal',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'ef_user',
					'operator' => '==',
					'value' => 'all',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}

?>
