<?php
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_user-fields',
		'title' => 'User Fields',
		'fields' => array (
			array (
				'key' => 'field_57defc3a86004',
				'label' => 'Please verify that your products are eligible for at least one of the following programs',
				'name' => 'certified',
				'type' => 'checkbox',
				'choices' => array (
					'50' => '<div class="register__checkbox">At least 50% of value added in Hawaii <br> <a href="#">See calculator in application form</a></div>',
					'100' => '<div class="register__checkbox">100% grown in Hawaii</div>',
					'seal' => '<div class="register__checkbox">Premium product with at least 50% local ingredients or 100% grown in Hawaii</div>',
				),
				'default_value' => '',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_57cdfbeef278a',
				'label' => 'Type Of Business',
				'name' => 'type_of_business',
				'type' => 'checkbox',
				'choices' => array (
					'grower' => 'grower',
					'distributor' => 'distributor',
					'wholesaler' => 'wholesaler',
					'processor' => 'processor',
					'manufacturer' => 'manufacturer',
					'retailer' => 'retailer',
				),
				'default_value' => '',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_57defc0d86003',
				'label' => 'Help',
				'name' => '',
				'type' => 'message',
				'message' => 'Help us setup your Made in Hawaii producer profile',
			),
			array (
				'key' => 'field_57c670d559d68',
				'label' => 'Address',
				'name' => 'address',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57c670dc59d69',
				'label' => 'City',
				'name' => 'city',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57c670e259d6a',
				'label' => 'State',
				'name' => 'state',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57c670e859d6b',
				'label' => 'Zip Code',
				'name' => 'zip',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '96701', //Added constraint
				'max' => '96898',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57c670ee59d6c',   //This would be cleaner as a drop down
				'label' => 'Island',
				'name' => 'island',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57c670f559d6d',
				'label' => 'Sales Phone Number',
				'name' => 'phone1',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57c670fd59d6e',
				'label' => 'Secondary Phone Number',
				'name' => 'phone2',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57c6711159d71',
				'label' => 'Website',
				'name' => 'website',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://',  //modified
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' =>  'field_57c6712959d74',  //Field info stolen from Country
				'label' => 'Instagram',
				'name' => 'instagram',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57c6711c59d72',
				'label' => 'Sales Email',
				'name' => 'email',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'This will be provided to potential buyers',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57c6712e59d75',
				'label' => 'Year Established',
				'name' => 'established_year',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '1800', //Added constraint
				'max' => '2100',
				'step' => '',
			),
			array (
				'key' => 'field_57cdfc28f278b',
				'label' => 'Services',
				'name' => 'services',
				'type' => 'checkbox',
				'choices' => array (
					'mailorder' => 'Mail Order',
					'delivery' => 'Delivery',
					'catering' => 'Catering',
					'packing' => 'Packing', //Where did we get this one from?
					'growing' => 'Growing', //Where did we get this one from?
					'labeling' => 'Private Labeling',
					'bulk' => 'Bulk',
					'retail' => 'Retail',
					'wholesale' => 'Wholesale',
				),
				'default_value' => '',
				'layout' => 'horizontal',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'ef_user',
					'operator' => '==',
					'value' => 'all',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}

?>
